using Backend_session9;
using Backend_session9.Models;
using Microsoft.EntityFrameworkCore;

namespace Backend_session9
{
    public class Program
    {
        // Static context — EF Core manages the DB connection automatically
        public static EcommerceContext context = new EcommerceContext();

        // ─────────────────────────────────────────────────────────────────────
        // USER FUNCTIONS
        // ─────────────────────────────────────────────────────────────────────

        public static void RegisterUser()
        {
            Console.WriteLine("\n=== Register New User ===");

            Console.Write("Enter username: ");
            string name = Console.ReadLine();

            Console.Write("Enter email: ");
            string email = Console.ReadLine();

            Console.Write("Enter password: ");
            string password = Console.ReadLine();
            string passwordHash = password; // In production: BCrypt.Hash(password)

            Console.Write("Enter full name: ");
            string fullName = Console.ReadLine();

            Console.Write("Enter phone number (optional, Enter to skip): ");
            string phone = Console.ReadLine();

            Console.Write("Enter address (optional, Enter to skip): ");
            string address = Console.ReadLine();

            context.Users.Add(new User
            {
                //Id generated by SQL Server (Identity) in database, no need to set it here
                Name = name,
                email = email,
                passwordHash = passwordHash,
                fullName = fullName,
                phoneNumber = string.IsNullOrWhiteSpace(phone) ? null : phone,
                address = string.IsNullOrWhiteSpace(address) ? null : address,
                registrationDate = DateTime.Now,
                isActive = true
            });

            context.SaveChanges(); // INSERT INTO Users

            User saved = context.Users.OrderBy(u => u.userId).Last();
            Console.WriteLine($"User registered successfully. Assigned ID: {saved.userId}");



            ////////////////////////

            var SelectedProduct = context.Products.Include(p => p.Reviews)
                                                  .Include(p=>p.OrderItems)
                                                  .FirstOrDefault(p => p.price > 50);


            foreach(Review r in SelectedProduct.Reviews)
            {
                Console.WriteLine($"Review ID: {r.reviewId}, Rating: {r.rating}, Comment: {r.comment}");
            }

        }

        public static void ViewAllUsers()
        {
            Console.WriteLine("\n=== All Users ===");

            // SELECT * FROM Users
            List<User> users = context.Users.ToList();

            foreach (User u in users)
                Console.WriteLine($"ID: {u.userId}  |  Username: {u.Name}  |  Name: {u.fullName}" +
                                  $"  |  Email: {u.email}  |  Active: {u.isActive}");
        }

        // ─────────────────────────────────────────────────────────────────────
        // CATEGORY FUNCTIONS
        // ─────────────────────────────────────────────────────────────────────

        public static void AddCategory()
        {
            Console.WriteLine("\n=== Add New Category ===");

            Console.Write("Enter category name: ");
            string name = Console.ReadLine();

            Console.Write("Enter description (optional): ");
            string desc = Console.ReadLine();

            context.Categories.Add(new Category
            {
                categoryName = name,
                description = string.IsNullOrWhiteSpace(desc) ? null : desc
            });

            context.SaveChanges(); // INSERT INTO Categories

            Category saved = context.Categories.OrderBy(c => c.categoryId).Last();
            Console.WriteLine($"Category added. ID: {saved.categoryId}");
        }

        public static void ViewAllCategories()
        {
            Console.WriteLine("\n=== All Categories ===");

            // SELECT * FROM Categories
            List<Category> categories = context.Categories.ToList();

            foreach (Category c in categories)
                Console.WriteLine($"ID: {c.categoryId}  |  Name: {c.categoryName}  |  Desc: {c.description}");
        }

        // ─────────────────────────────────────────────────────────────────────
        // PRODUCT FUNCTIONS
        // ─────────────────────────────────────────────────────────────────────

        public static void AddProduct()
        {
            Console.WriteLine("\n=== Add New Product ===");

            // SELECT * FROM Categories
            List<Category> categories = context.Categories.ToList();
            Console.WriteLine("Available categories:");
            foreach (Category c in categories)
                Console.WriteLine($"  ID: {c.categoryId}  |  {c.categoryName}");

            Console.Write("Enter category ID: ");
            int categoryId = int.Parse(Console.ReadLine());

            Console.Write("Enter product name: ");
            string name = Console.ReadLine();

            Console.Write("Enter description (optional): ");
            string desc = Console.ReadLine();

            Console.Write("Enter price: ");
            double price = double.Parse(Console.ReadLine());

            Console.Write("Enter stock quantity: ");
            int stock = int.Parse(Console.ReadLine());

            context.Products.Add(new Product
            {
                productName = name,
                description = string.IsNullOrWhiteSpace(desc) ? null : desc,
                price = price,
                stockQuantity = stock,
                categoryId = categoryId,
                createdAt = DateTime.Now,
                isAvailable = true
            });

            context.SaveChanges(); // INSERT INTO Products

            Product saved = context.Products.OrderBy(p => p.productId).Last();
            Console.WriteLine($"Product added. ID: {saved.productId}");
        }

        public static void ViewAllProducts()
        {
            Console.WriteLine("\n=== All Products ===");

            // SELECT * FROM Products JOIN Categories (via Include)
            List<Product> products = context.Products
                .Include(p => p.c)   // loads Category navigation property => JOIN
                .ToList();

            foreach (Product p in products)
                Console.WriteLine($"ID: {p.productId}  |  {p.productName}  |  Price: {p.price:C}" +
                                  $"  |  Stock: {p.stockQuantity}  |  Category: {p.c.categoryName}" +
                                  $"  |  Available: {p.isAvailable}");
        }

        // replacing the previous ViewProductsByCategory with EF Core Include
        public static void ViewProductsByCategory()
        {
            Console.WriteLine("\n=== View Products by Category ===");

            List<Category> categories = context.Categories.ToList();
            Console.WriteLine("Categories:");
            foreach (Category c in categories)
                Console.WriteLine($"  ID: {c.categoryId}  |  {c.categoryName}");

            Console.Write("Enter category ID: ");
            int categoryId = int.Parse(Console.ReadLine());

            // SELECT category WITH its Products loaded via Include
            Category category = context.Categories
                .Include(c => c.Products)
                .FirstOrDefault(c => c.categoryId == categoryId);

            Console.WriteLine($"\nProducts in '{category.categoryName}':");
            foreach (Product p in category.Products)
                Console.WriteLine($"  ID: {p.productId}  |  {p.productName}  |  {p.price:C}  |  Stock: {p.stockQuantity}");
        }

        // ─────────────────────────────────────────────────────────────────────
        // ORDER FUNCTIONS
        // ─────────────────────────────────────────────────────────────────────

        public static void PlaceOrder()
        {
            Console.WriteLine("\n=== Place New Order ===");

            List<User> users = context.Users.ToList();
            Console.WriteLine("Users:");
            foreach (User u in users)
                Console.WriteLine($"  ID: {u.userId}  |  {u.Name}");

            Console.Write("Enter user ID: ");
            int userId = int.Parse(Console.ReadLine());

            Console.Write("Enter shipping address: ");
            string shippingAddress = Console.ReadLine();

            Console.WriteLine("Payment methods: 1-CreditCard  2-DebitCard  3-PayPal  4-Cash");
            Console.Write("Choose payment method: ");
            int payChoice = int.Parse(Console.ReadLine());
            string[] payMethods = { "CreditCard", "DebitCard", "PayPal", "Cash" };
            string paymentMethod = payMethods[payChoice - 1];

            // INSERT the order first to get orderId from DB
            Order order = new Order
            {
                userId = userId,
                orderDate = DateTime.Now,
                totalAmount = 0,
                status = "Pending",
                shippingAddress = shippingAddress,
                paymentMethod = paymentMethod
            };
            context.Orders.Add(order);
            context.SaveChanges(); // orderId now assigned by SQL Server

            while (true)
            {
                List<Product> available = context.Products
                    .Where(p => p.isAvailable && p.stockQuantity > 0)
                    .ToList();

                Console.WriteLine("\nAvailable products:");
                foreach (Product p in available)
                    Console.WriteLine($"  ID: {p.productId}  |  {p.productName}  |  {p.price:C}  |  Stock: {p.stockQuantity}");

                Console.Write("Enter product ID to add (0 to finish): ");
                int productId = int.Parse(Console.ReadLine());
                if (productId == 0) break;

                Product product = context.Products.FirstOrDefault(p => p.productId == productId);

                Console.Write("Enter quantity: ");
                int qty = int.Parse(Console.ReadLine());

                // INSERT OrderItem
                context.OrderItems.Add(new OrderItem
                {
                    orderId = order.orderId,
                    productId = productId,
                    quantity = qty,
                    unitPrice = (decimal)product.price // price snapshot at time of ordering
                });

                // UPDATE Product stock and Order total (EF Core tracks these changes)
                product.stockQuantity -= qty;
                order.totalAmount += (decimal)product.price * qty;

                context.SaveChanges(); // INSERT OrderItem + UPDATE Product + UPDATE Order
            }

            Console.WriteLine($"\nOrder placed! Order ID: {order.orderId}  |  Total: {order.totalAmount:C}");
        }

        public static void ViewOrderHistory()
        {
            Console.WriteLine("\n=== Order History ===");

            List<User> users = context.Users.ToList();
            Console.WriteLine("Users:");
            foreach (User u in users)
                Console.WriteLine($"  ID: {u.userId}  |  {u.Name}");

            Console.Write("Enter user ID: ");
            int userId = int.Parse(Console.ReadLine());

            // SELECT User + Orders + OrderItems + Products in one chained Include
            User user = context.Users
                .Include(u => u.Orders)
                    .ThenInclude(o => o.OrderItems)
                        .ThenInclude(i => i.Product)
                .FirstOrDefault(u => u.userId == userId);

            Console.WriteLine($"\nOrders for {user.fullName}:");
            foreach (Order o in user.Orders)
            {
                Console.WriteLine($"\n  Order ID: {o.orderId}  |  Date: {o.orderDate:d}" +
                                  $"  |  Status: {o.status}  |  Total: {o.totalAmount:C}");
                foreach (OrderItem item in o.OrderItems)
                    Console.WriteLine($"    - {item.Product.productName}  x{item.quantity}  @ {item.unitPrice:C}");
            }

            decimal grandTotal = user.Orders.Sum(o => o.totalAmount);
            Console.WriteLine($"\n  TOTAL SPENT: {grandTotal:C}");
        }

        // ─────────────────────────────────────────────────────────────────────
        // REVIEW FUNCTIONS
        // ─────────────────────────────────────────────────────────────────────

        public static void WriteReview()
        {
            Console.WriteLine("\n=== Write a Review ===");

            List<User> users = context.Users.ToList();
            Console.WriteLine("Users:");
            foreach (User u in users)
                Console.WriteLine($"  ID: {u.userId}  |  {u.Name}");
            Console.Write("Enter user ID: ");
            int userId = int.Parse(Console.ReadLine());

            List<Product> products = context.Products.ToList();
            Console.WriteLine("\nProducts:");
            foreach (Product p in products)
                Console.WriteLine($"  ID: {p.productId}  |  {p.productName}");
            Console.Write("Enter product ID to review: ");
            int productId = int.Parse(Console.ReadLine());

            Console.Write("Enter rating (1-5): ");
            int rating = int.Parse(Console.ReadLine());

            Console.Write("Enter comment (optional): ");
            string comment = Console.ReadLine();

            context.Reviews.Add(new Review
            {
                userId = userId,
                productId = productId,
                rating = rating,
                comment = string.IsNullOrWhiteSpace(comment) ? null : comment,
                reviewDate = DateTime.Now
            });

            context.SaveChanges(); // INSERT INTO Reviews

            Review saved = context.Reviews.OrderBy(r => r.reviewId).Last();
            Console.WriteLine($"Review submitted! Review ID: {saved.reviewId}");
        }

        public static void ViewProductReviews()
        {
            Console.WriteLine("\n=== Product Reviews ===");

            List<Product> products = context.Products.ToList();
            Console.WriteLine("Products:");
            foreach (Product p in products)
                Console.WriteLine($"  ID: {p.productId}  |  {p.productName}");

            Console.Write("Enter product ID: ");
            int productId = int.Parse(Console.ReadLine());

            Product product = context.Products.FirstOrDefault(p => p.productId == productId);

            // SELECT Reviews WHERE productId = x  JOIN Users
            List<Review> reviews = context.Reviews
                .Include(r => r.U)               // JOIN Users table
                .Where(r => r.productId == productId)
                .ToList();

            Console.WriteLine($"\nReviews for '{product.productName}':");
            foreach (Review r in reviews)
            {
                Console.WriteLine($"  [{r.rating}/5] by {r.U.fullName} on {r.reviewDate:d}");
                if (!string.IsNullOrWhiteSpace(r.comment))
                    Console.WriteLine($"    \"{r.comment}\"");
            }

            if (reviews.Count > 0)
            {
                double avg = reviews.Average(r => r.rating);
                Console.WriteLine($"\n  Average Rating: {avg:F1} / 5.0  ({reviews.Count} reviews)");
            }
            else
            {
                Console.WriteLine("  No reviews yet.");
            }
        }

        // ─────────────────────────────────────────────────────────────────────
        // MAIN — Menu loop
        // ─────────────────────────────────────────────────────────────────────
        static void Main(string[] args)
        {
            bool exit = false;

            while (!exit)
            {
                Console.WriteLine("\n========================================");
                Console.WriteLine("        E-Commerce System");
                Console.WriteLine("========================================");
                Console.WriteLine(" 1  - Register User");
                Console.WriteLine(" 2  - View All Users");
                Console.WriteLine(" 3  - Add Category");
                Console.WriteLine(" 4  - View All Categories");
                Console.WriteLine(" 5  - Add Product");
                Console.WriteLine(" 6  - View All Products");
                Console.WriteLine(" 7  - View Products by Category");
                Console.WriteLine(" 8  - Place Order");
                Console.WriteLine(" 9  - View Order History");
                Console.WriteLine(" 10 - Write a Review");
                Console.WriteLine(" 11 - View Product Reviews");
                Console.WriteLine(" 0  - Exit");
                Console.WriteLine("========================================");
                Console.Write("Select option: ");

                int option = int.Parse(Console.ReadLine());

                switch (option)
                {
                    case 1: RegisterUser(); break;
                    case 2: ViewAllUsers(); break;
                    case 3: AddCategory(); break;
                    case 4: ViewAllCategories(); break;
                    case 5: AddProduct(); break;
                    case 6: ViewAllProducts(); break;
                    case 7: ViewProductsByCategory(); break;
                    case 8: PlaceOrder(); break;
                    case 9: ViewOrderHistory(); break;
                    case 10: WriteReview(); break;
                    case 11: ViewProductReviews(); break;
                    case 0: exit = true; break;
                    default: Console.WriteLine("Invalid option. Please try again."); break;
                }

                if (!exit)
                {
                    Console.WriteLine("\nPress any key to continue...");
                    Console.ReadKey();
                    Console.Clear();
                }
            }

            Console.WriteLine("Goodbye!");
        }
    }
}
